### ISSUE TITLE
[bug]: Embassy about shows incorrect LAN address

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1057]
The LAN address returned from the backend seems to be `embassy.local` when it should be `embassy-<hostname>.local`:

<img width="2556" alt="Screen Shot 2022-01-12 at 5 27 48 PM" src="https://user-images.githubusercontent.com/12953208/149248682-1a3e2058-c2f3-4490-b1f1-5d4d5e22d672.png">

In `/etc/nginx/sites-available/default`, the server name directive reads as below, but I am unsure if this is intentional:
`server_name .embassy.local;`

**Comment by dr-bonez** [comment]
this was fixed by #987. Are you sure you just didn't perform setup before that?

**Comment by Blu-J** [comment]
Mines
![image](https://user-images.githubusercontent.com/2364004/149421585-43e7d051-042c-4a84-be02-e63d0a0de002.png)

And Lucy's git tag is recent, so this is a weird state. That gets recreated every bootup right, there wont be a weird state from quick flashing will there?

**Comment by ProofOfKeags** [comment]
@DrewAns @MattDHill is this information stored in either local storage or the FE patchdb state? If so, it probably ought not to be. I can confirm that my current build behaves in the way that you would expect.

**Comment by MattDHill** [comment]
No, this is 100% regurgitates from patchDB BE state, server['lan-address']

**Comment by elvece** [comment]
I just reflashed with balena at b50e7ebd306af917652c46629f5d7b86ba164131 and setup (recovered), and it is still showing as `embassy.local`:
<img width="1674" alt="Screen Shot 2022-01-14 at 12 52 54 PM" src="https://user-images.githubusercontent.com/12953208/149576843-fded1271-e8d6-4a39-92e7-49f910dfdce1.png">

**Comment by ProofOfKeags** [comment]
This is the result of never updating patchdb state during setup or recovery.

**Comment by ProofOfKeags** [comment]
At this point I am confident that I cannot handle this on my own. This seemingly innocuous bug actually has very far reaching relationships. At its core, this bug is due to the fact that we don't have a canonical source of truth for what the LAN address is. Further, one of the important properties of the LAN address is that it is linked to the product key because the server id is the first 8 hex digits of the sha256 hash of the product key.

This problem presents during any sort of non-fresh setup. In order for us to reestablish consistency we must make it such that the product key is the source of truth for the LAN address, and its presence in patchdb is essentially just a cache of this calculation to serve to the front end. If this is the case, it means that LAN addresses will not always remain the same when restoring from a backup or attaching a drive. Why? Because the product key is bound to the image and not to the data volume, as such there is no way to ascertain the product key that produced the patchdb LAN address value. The one exception to this is when it is being restored from 0.2. This is because the product key *does* live on the data volume in the 0.2 case.

All this leaves us with the following solution:
1. When migrating from 0.2, the product key that is read from the 0.2 data must be used to *overwrite* the product key that is on the 0.3.0 image. We already have to do this anyway in the case where there is no product key present on the 0.3.0 device.
2. In all setup flows, we must derive the server id from the product key and shove the corresponding LAN address into patchdb and report *that* LAN address back in the setup result.

At present it does not appear that we have any means of writing to patchdb with the `SetupContext` alone which makes it very hard to keep things in sync. It *does* look like patchdb is constructable at those sites but I'm not sure if that is safe to do. If we can get into patchdb in the setup contexts, that solves this problem handily.
