### ISSUE TITLE
[bug]: `database is locked`

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1317]
occasionally requests will error with `Database Error: database is locked`. This can be fixed by updating to sqlx v0.5.11.

**Comment by MattDHill** [comment]
Should be fixed by 0311, but leaving open to confirm with public usage

**Comment by chrisguida** [comment]
Do you have a link to the fix?

**Comment by chrisguida** [comment]
🙏

**Comment by chrisguida** [comment]
Looks like it was still broken in June: https://github.com/Start9Labs/embassy-os/issues/1529

**Comment by dr-bonez** [comment]
should be fixed by #1763
